name: CI/CD Pipeline for House Price API

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_IMAGE: a18ab77c4b90/house-price-api
      KUBE_CONFIG_PATH: ~/.kube/config

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE:latest .
        docker push $DOCKER_IMAGE:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.0'

    - name: Configure kubeconfig
      env:
        KUBE_CONFIG_PATH: $HOME/.kube/config
      run: |
        mkdir -p $(dirname $KUBE_CONFIG_PATH)
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > $KUBE_CONFIG_PATH
        chmod 600 $KUBE_CONFIG_PATH


    - name: Deploy to K3s cluster
      run: |
        kubectl set image deployment/house-price-api house-price-api=$DOCKER_IMAGE:latest
